spring:
  application:
    # 指定发布的微服务名（以后调用时，只需该名称即可访问该服务）
    name: MonthReporter
  #配置druid数据源
#  datasource:
#    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://10.83.16.9:3306/tencent_credit_investigation?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#      username: root
#      password: Xfx2018@)!*
#      #连接池大小
#      initial-size: 30
#      #连接池最小连接数
#      min-idle: 10
#      #连接池最大连接数
#      max-active: 50
#      #获取连接等待超时时间
#      max-wait: 1000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      max-pool-prepared-statement-per-connection-size: 20
#      pool-prepared-statements: true
#      max-open-prepared-statements: 100
#      time-between-log-stats-millis: 300000
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filter: stat,wall,log4j
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connect-properties: config.decrypt=false
#      remove-abandoned: true
#      remove-abandoned-timeout: 1800
#      log-abandoned: false
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.83.16.9:3306/tencent_credit_investigation?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: Xfx2018@)!*
      #连接池大小
      druid:
       # 连接池的配置信息
       # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
       # 配置获取连接等待超时的时间
        maxWait: 60000
       # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
       # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
       # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
       # 配置监控统计拦截的filters，去掉后监控界面sql无法统
#配置mybatis
mybatis:
  type-aliases-package:
  #所有mapper文件映射路径
  mapper-locations: classpath:mapper/*.xml
  #mybatis的配置文件
  #config-location: classpath:mybatis-config.xml

#开启日志
#
#显示执行SQL语句
logging:
  level:
    com:
      weshareholdings:
        xinyan:
          dao: debug